spring:
  cloud:
    config:
      import-check:
        enabled: false
  application:
    name: myapp
#### Pool de conexao ####
  datasource:
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 8
      initialization-fail-timeout: 2000
      isolate-internal-queries: true
      validation-timeout: 3000
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/example?authSource=admin
  lifecycle:
    timeout-per-shutdown-phase: 20s

  zipkin:
    base-url: http://localhost:9411
  sleuth:
    enabled: true
    sampler:
      probability: 1.0

server:
  port: 8080
  shutdown: graceful

### OpenTracing ###
opentracing:
  jaeger:
    enabled: ${JAEGER_ENABLED:true}
    service-name: ${spring.application.name}
    http-sender:
      url: ${JAEGER_ENDPOINT:http://localhost:14268/api/traces}
    probabilistic-sampler:
      sampling-rate: ${JAEGER_SAMPLER:1}
  spring:
    cloud:
      jdbc:
        enabled: false

management:
  health:
    mongo:
      enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health,metrics,info,prometheus"
      percentiles:
        http:
          server:
            requests: 0.5,0.9,0.95,0.99,0.999
